config/routes.rb
Vendorguide::Application.routes.draw do

  root :to => "vendors#index"
  resources :vendors
  resources :reviews
  devise_for :users

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :user
  validates_presence_of :vendor
  validates_presence_of :score
  validates_presence_of :description
  validates_numericality_of :score
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :oauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :facebook_token, :facebook_id, :first_name, :last_name

  validates_presence_of :facebook_token


  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = ActiveSupport::JSON.decode(access_token.get('https://graph.facebook.com/me?'))
    facebook_user = Mogli::User.find("me", Mogli::Client.new(access_token.token))
    user_attributes = {:facebook_token => access_token.token, :facebook_id => facebook_user.id, :first_name => facebook_user.first_name, :last_name => facebook_user.last_name}
    if user = User.find_by_email(data["email"])
      user.update_attributes(user_attributes)
      user
    else # Create an user with a stub password.
      User.create!({:email => data["email"], :password => Devise.friendly_token[0,20]}.merge(user_attributes))
    end
  end

  def name
    "#{first_name} #{last_name[0]}."
  end

  def facebook_client
    @client ||= Mogli::Client.new(facebook_token)
  end

  def me
    @me ||= Mogli::User.find("me", facebook_client)
  end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :reviews
  belongs_to :user

  validates_presence_of :name
  validates_presence_of :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :authenticate_user!


  def create
    @review = Review.new params[:review]
    @review.user = current_user

    if @review.save
      redirect_to @review.vendor
    else
      render :action => 'new'
    end
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @vendors = Vendor.all
  end

  def new
    @vendor = Vendor.new
  end

  def show
    @vendor = Vendor.find params[:id]
    @review = Review.new :vendor => @vendor, :user => @current_user
  end

  def create
    @vendor = Vendor.create params[:vendor]

    if @vendor.valid?
      redirect_to @vendor
    else
      render :action => 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/home/index.html.haml
%h2 Vendor Guide

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Vendor Guide
    = stylesheet_link_tag 'compiled/screen'
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    .header
      .login
        - if current_user
          .login-info
            = "#{current_user.me.first_name} #{current_user.me.last_name}"
            = link_to "Logout", destroy_user_session_path
          .login-image
            = image_tag current_user.me.square_image_url, :width => '25px', :height => '25px'
        - else
          .login-info
            = link_to "Sign in as User with Facebook", user_oauth_authorize_url(:facebook)
      <div style="clear: both;"></div>
    .content
      .messages
        - flash.each do |key, msg|
          %div{'class' => key}
            = msg

      = yield

app/views/reviews/_form.html.haml
= semantic_form_for @review do |form|
  - form.inputs do
    = form.input :description, :as => :text
    = form.input :score,       :as => :select, :collection => ["1", "2", "3", "4", "5"]
    = form.input :vendor_id,    :as => :hidden, :value => @review.vendor.id
  - form.buttons do
    = form.commit_button

app/views/reviews/new.html.haml
%h2
  Add Review for
  = @review.vendor.name
= render :partial => 'form'

app/views/vendors/_form.html.haml
= semantic_form_for @vendor do |form|
  - form.inputs do
    = form.input :name
    = form.input :description, :as => :text
  - form.buttons do
    = form.commit_button

app/views/vendors/index.html.haml
%h2 Vendor Guide
.add-vendor
  = link_to "Add a Vendor", new_vendor_path

- if @vendors.any?
  - @vendors.each do |vendor|
    .vendor-mini
      = link_to vendor.name, vendor

app/views/vendors/new.html.haml
%h2 New Vendor

= render :partial => 'form'

app/views/vendors/show.html.haml
.vendor
  %h2
    = @vendor.name
  .description
    = @vendor.description
  .reviews
    - @vendor.reviews.each do |review|
      .review-inline
        .author
          = review.user.name
        = review.description
    %hr
    - if current_user
      %h3
        Add Your Review
      = render :partial => 'reviews/form'
    - else
      = link_to "Sign in with Facebook to add a review", user_oauth_authorize_url(:facebook)